sonar.projectKey=gryphus-lab_zurich-search-aggregator
sonar.organization=gryphus-lab

sonar.projectName=zurich-search-aggregator

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.exclusions=**/__pycache__/**, **/*.pyc, **/results/**, **/coverage.xml
sonar.python.coverage.reportPaths=coverage.xml

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
sonar.python.version=3.14
